#!/bin/bash -l

#SBATCH --account=jcap
#SBATCH --nodes=1
#SBATCH --ntasks-per-node=32
#SBATCH --qos=normal
#SBATCH --time=00:12:00
#SBATCH --partition=debug
#SBATCH --job-name=relax
#SBATCH --output=relax-%j.out
#SBATCH --error=relax-%j.error
#SBATCH --constraint=haswell


cd /global/cscratch1/sd/krisb/fireworks/jobs/relax_2017_12_08_15_31_50
cd /global/cscratch1/sd/krisb/fireworks;rlaunch singleshot --fw_id 4231

# CommonAdapter (SLURM) completed writing Template
