#!/bin/bash -l

#SBATCH --nodes=1
#SBATCH --ntasks-per-node=16
#SBATCH --time=04:00:00
#SBATCH --partition=iric
#SBATCH --job-name=relax
#SBATCH --output=relax-%j.out
#SBATCH --error=relax-%j.error

source /scratch/PI/suncat/sw/env.bash;source ~/.bashrc
cd /scratch/users/mstatt/fireworks/jobs/relax_2017_11_09_16_10_51
cd /scratch/users/mstatt/fireworks;rlaunch singleshot --fw_id 1203

# CommonAdapter (SLURM) completed writing Template
